import { type NextPage } from "next";
import Head from "next/head";

import dynamic from "next/dynamic";
const SinglePeer = dynamic(() => import("../components/SinglePeer"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>WebRTC - Single Peer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <SinglePeer />
      </main>
    </>
  );
};

export default Home;
